TELEGRAM:
  API_ID: 123456
  API_HASH: "YOUR_API_HASH_HERE"
  BOT_TOKEN: "YOUR_BOT_TOKEN_HERE"

SYSTEM:
  WORK_DIR: "YOUR_WORK_DIR_HERE"
  COOKIE_FILE: "YOUR_COOKIE_FILE_NAME_HERE"

TOKENS:
  X_AUTH_TOKEN: "YOUR_X_AUTH_TOKEN_HERE"
  X_CT0: "YOUR_X_CT0_HERE"

  INS_SESSIONID: "YOUR_INSTAGRAM_SESSIONID_HERE"
  INS_CSRFTOKEN: "YOUR_INS_CSRFTOKEN_HERE"
