import os
import tempfile
import threading
import time
from dataclasses import dataclass

import yaml


PLATFORM_ALIASES = {
    "x": "x",
    "twitter": "x",
    "instagram": "instagram",
    "ig": "instagram",
}

REQUIRED_COOKIES = {
    "x": {"auth_token", "ct0"},
    "instagram": {"sessionid", "csrftoken"},
}

AUTH_ERROR_KEYWORDS = (
    "login required",
    "login_required",
    "authentication required",
    "authentication credentials",
    "not logged in",
    "cookie",
    "cookies",
    "unauthorized",
    "forbidden",
    "http error 401",
    "http error 403",
    "401 unauthorized",
    "403 forbidden",
    "checkpoint",
    "challenge_required",
    "challenge required",
)

X_COOKIE_HINT_ERROR_KEYWORDS = (
    "no video could be found in this tweet",
)

RATE_LIMIT_KEYWORDS = (
    "too many requests",
    "rate limit",
    "ratelimit",
    "http error 429",
    "429 too many requests",
)


@dataclass
class CookieStatus:
    platform: str
    source: str
    state: str
    path: str = ""
    updated_at: float = 0
    reason: str = ""


def _normalize_platform(platform):
    return PLATFORM_ALIASES.get((platform or "").lower())


def normalize_platform(platform):
    return _normalize_platform(platform)


def platform_from_url(url):
    value = (url or "").lower()
    if "instagram.com" in value:
        return "instagram"
    if "x.com" in value or "twitter.com" in value:
        return "x"
    return None


def _is_valid_token(token):
    if not token or not isinstance(token, str):
        return False
    token = token.strip()
    if not token:
        return False
    invalid_keywords = ("你的", "填这里", "your", "YOUR")
    if any(keyword in token for keyword in invalid_keywords):
        return False
    if len(token) < 10:
        return False
    return True


def _atomic_write(path, content):
    directory = os.path.dirname(path) or "."
    os.makedirs(directory, exist_ok=True)
    fd, tmp_path = tempfile.mkstemp(prefix=".cookies-", dir=directory)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as tmp:
            tmp.write(content)
        os.chmod(tmp_path, 0o600)
        os.replace(tmp_path, path)
        os.chmod(path, 0o600)
    finally:
        if os.path.exists(tmp_path):
            os.remove(tmp_path)


class CookieManager:
    def __init__(self, config_path="config.yaml"):
        self.config_path = config_path
        self.lock = threading.RLock()
        self.last_admin_alert = {}
        self.reload()

    def reload(self):
        with self.lock:
            with open(self.config_path, "r", encoding="utf-8") as f:
                self.config = yaml.safe_load(f) or {}

            system_cfg = self.config.get("SYSTEM", {})
            self.work_dir = system_cfg.get("WORK_DIR", "./")
            os.makedirs(self.work_dir, exist_ok=True)

            cookies_cfg = self.config.get("COOKIES", {})
            self.mode = (cookies_cfg.get("MODE") or "file").lower()
            if self.mode not in ("file", "tokens", "none"):
                self.mode = "file"

            self.generated_cookie_path = self._resolve_path(
                cookies_cfg.get("TOKEN_COOKIE_FILE", "generated.cookies.txt")
            )
            self.cookie_paths = {
                "x": self._resolve_path(cookies_cfg.get("X_COOKIE_FILE", "x.cookies.txt")),
                "instagram": self._resolve_path(
                    cookies_cfg.get("INSTAGRAM_COOKIE_FILE", "instagram.cookies.txt")
                ),
            }
            self.upload_session_ttl = int(cookies_cfg.get("UPLOAD_SESSION_TTL_SECONDS", 600))
            self.admin_alert_cooldown = int(
                cookies_cfg.get("ADMIN_ALERT_COOLDOWN_SECONDS", 1800)
            )

            admin_cfg = self.config.get("ADMIN", {})
            self.admin_user_ids = {
                int(user_id)
                for user_id in admin_cfg.get("USER_IDS", [])
                if str(user_id).strip().isdigit()
            }

            self._write_token_cookie_file()

    def _resolve_path(self, path):
        if os.path.isabs(path):
            return path
        return os.path.join(self.work_dir, path)

    def _write_token_cookie_file(self):
        tokens = self.config.get("TOKENS", {})
        lines = [
            "# Netscape HTTP Cookie File",
            "# This file is automatically generated from TOKENS by bot.",
            "",
        ]

        x_token = tokens.get("X_AUTH_TOKEN")
        x_ct0 = tokens.get("X_CT0")
        ins_token = tokens.get("INS_SESSIONID")
        ins_csrf = tokens.get("INS_CSRFTOKEN")

        if _is_valid_token(x_token):
            value = x_token.strip()
            lines.append(f".twitter.com\tTRUE\t/\tTRUE\t2000000000\tauth_token\t{value}")
            lines.append(f".x.com\tTRUE\t/\tTRUE\t2000000000\tauth_token\t{value}")
        if _is_valid_token(x_ct0):
            value = x_ct0.strip()
            lines.append(f".twitter.com\tTRUE\t/\tTRUE\t2000000000\tct0\t{value}")
            lines.append(f".x.com\tTRUE\t/\tTRUE\t2000000000\tct0\t{value}")
        if _is_valid_token(ins_token):
            value = ins_token.strip()
            lines.append(f".instagram.com\tTRUE\t/\tTRUE\t2000000000\tsessionid\t{value}")
        if _is_valid_token(ins_csrf):
            value = ins_csrf.strip()
            lines.append(f".instagram.com\tTRUE\t/\tTRUE\t2000000000\tcsrftoken\t{value}")

        if len(lines) > 3:
            _atomic_write(self.generated_cookie_path, "\n".join(lines) + "\n")
        elif self._is_generated_cookie_file(self.generated_cookie_path):
            os.remove(self.generated_cookie_path)

    def _is_generated_cookie_file(self, path):
        if not os.path.exists(path):
            return False
        try:
            with open(path, "r", encoding="utf-8", errors="replace") as f:
                head = f.read(512)
        except OSError:
            return False
        return "automatically generated from TOKENS by bot" in head

    def validate_cookie_file(self, path, platform):
        platform = _normalize_platform(platform)
        if not platform:
            return CookieStatus("", "file", "invalid", path, reason="未知平台")
        if not path or not os.path.exists(path):
            return CookieStatus(platform, "file", "missing", path, reason="文件不存在")

        now = int(time.time())
        required = REQUIRED_COOKIES[platform]
        found = set()
        expired = set()

        try:
            with open(path, "r", encoding="utf-8", errors="replace") as f:
                for raw_line in f:
                    line = raw_line.strip()
                    if not line or line.startswith("#"):
                        continue
                    parts = line.split("\t")
                    if len(parts) < 7:
                        continue
                    expires, name, value = parts[4], parts[5], parts[6]
                    if name not in required or not value:
                        continue
                    try:
                        expiry = int(expires)
                    except ValueError:
                        expiry = 0
                    if expiry and expiry < now:
                        expired.add(name)
                    else:
                        found.add(name)
        except OSError as e:
            return CookieStatus(platform, "file", "invalid", path, reason=str(e))

        updated_at = os.path.getmtime(path)
        missing = required - found
        if not missing:
            return CookieStatus(platform, "file", "valid", path, updated_at)
        if missing == expired or expired:
            return CookieStatus(
                platform,
                "file",
                "expired",
                path,
                updated_at,
                reason=f"已过期或缺失: {', '.join(sorted(missing))}",
            )
        return CookieStatus(
            platform,
            "file",
            "missing",
            path,
            updated_at,
            reason=f"缺少: {', '.join(sorted(missing))}",
        )

    def _best_status_for_platform(self, platform):
        if self.mode == "none":
            return CookieStatus(platform, "none", "missing", reason="COOKIES.MODE=none")

        if self.mode == "file":
            file_status = self.validate_cookie_file(self.cookie_paths[platform], platform)
            if file_status.state == "valid":
                file_status.source = "file"
                return file_status

        token_status = self.validate_cookie_file(self.generated_cookie_path, platform)
        token_status.source = "tokens"
        if self.mode == "tokens":
            return token_status
        if token_status.state == "valid":
            return token_status

        file_status = self.validate_cookie_file(self.cookie_paths[platform], platform)
        file_status.source = "file"
        return file_status

    def status(self, platform=None):
        with self.lock:
            if platform:
                platform = _normalize_platform(platform)
                return self._best_status_for_platform(platform)
            return {
                "x": self._best_status_for_platform("x"),
                "instagram": self._best_status_for_platform("instagram"),
            }

    def get_ydl_cookie_opts(self, url):
        platform = platform_from_url(url)
        if not platform:
            return {}
        with self.lock:
            status = self._best_status_for_platform(platform)
            if status.state == "valid" and status.path:
                return {"cookiefile": status.path}
        return {}

    def save_uploaded_cookie(self, platform, content):
        platform = _normalize_platform(platform)
        if not platform:
            return False, "未知平台"
        if isinstance(content, bytes):
            content = content.decode("utf-8", errors="replace")
        if len(content.encode("utf-8", errors="replace")) > 2 * 1024 * 1024:
            return False, "Cookie 文件超过 2MB"
        if "# Netscape HTTP Cookie File" not in content[:4096]:
            return False, "不是 Netscape cookies.txt 格式"

        target_path = self.cookie_paths[platform]
        directory = os.path.dirname(target_path) or "."
        os.makedirs(directory, exist_ok=True)
        fd, tmp_path = tempfile.mkstemp(prefix=f".{platform}-upload-", dir=directory)
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as tmp:
                tmp.write(content)
            os.chmod(tmp_path, 0o600)
            status = self.validate_cookie_file(tmp_path, platform)
            if status.state != "valid":
                return False, status.reason or "Cookie 校验失败"
            os.replace(tmp_path, target_path)
            os.chmod(target_path, 0o600)
            return True, "Cookie 已更新"
        finally:
            if os.path.exists(tmp_path):
                os.remove(tmp_path)

    def mark_auth_failure(self, platform):
        platform = _normalize_platform(platform)
        if not platform:
            return False
        now = time.time()
        with self.lock:
            last_at = self.last_admin_alert.get(platform, 0)
            if now - last_at < self.admin_alert_cooldown:
                return False
            self.last_admin_alert[platform] = now
            return True

    def is_admin(self, user_id):
        return int(user_id or 0) in self.admin_user_ids


cookie_manager = CookieManager()


def get_ydl_cookie_opts(url):
    return cookie_manager.get_ydl_cookie_opts(url)


def is_cookie_auth_error(error, url=None):
    text = str(error).lower()
    if any(keyword in text for keyword in RATE_LIMIT_KEYWORDS):
        return False
    if platform_from_url(url) == "x" and any(
        keyword in text for keyword in X_COOKIE_HINT_ERROR_KEYWORDS
    ):
        return True
    return any(keyword in text for keyword in AUTH_ERROR_KEYWORDS)
