# main.py
import os
import re
import time
import asyncio
import yaml
from pyrogram import Client, filters
from pyrogram.types import InlineKeyboardMarkup, InlineKeyboardButton
from pyrogram.errors import MessageNotModified

from x_downloader import download_video_sync

# --- 将配置文件中的 Token 动态转写为 yt-dlp 可识别的 Netscape 格式 ---
def generate_unified_cookie_file(config):
    system_cfg = config.get('SYSTEM', {})
    tokens = config.get('TOKENS', {})

    # 确定生成的 Cookie 文件路径
    work_dir = system_cfg.get('WORK_DIR', './')
    cookie_filename = system_cfg.get('COOKIE_FILE', 'cookies.txt')
    cookie_path = os.path.join(work_dir, cookie_filename)

    def is_valid_token(token):

        # 1. 检查是否为空或非字符串
        if not token or not isinstance(token, str):
            return False
        token = token.strip()

        # 2. 检查是否为空字符串
        if not token:
            return False

        # 3. 检查是否包含预设的占位符关键字（根据 config.example.yaml 的预设内容）
        invalid_keywords = ["你的", "填这里", "your", "YOUR"]
        if any(keyword in token for keyword in invalid_keywords):
            return False

        # 4. 检查是否包含中文字符 (Token 通常是纯英文/数字/符号)
        if re.search(r'[\u4e00-\u9fa5]', token):
            return False

        # 5. 基础长度校验 (通常 auth_token 和 sessionid 都有一定长度，这里设定一个最低阈值防呆)
        if len(token) < 10:
            return False

        return True


        # 写入文件逻辑
    with open(cookie_path, 'w', encoding='utf-8') as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file is automatically generated by bot. Do not edit manually.\n\n")

        x_token = tokens.get('X_AUTH_TOKEN')
        x_ct0 = tokens.get('X_CT0')

        ins_token = tokens.get('INS_SESSIONID')
        ins_csrf = tokens.get('INS_CSRFTOKEN')

        # 写入 X (Twitter) 的 auth_token 和 ct0
        if is_valid_token(x_token):
            x_token_clean = x_token.strip()
            f.write(f".twitter.com\tTRUE\t/\tTRUE\t2000000000\tauth_token\t{x_token_clean}\n")
            f.write(f".x.com\tTRUE\t/\tTRUE\t2000000000\tauth_token\t{x_token_clean}\n")

        if is_valid_token(x_ct0):
            x_ct0_clean = x_ct0.strip()
            f.write(f".twitter.com\tTRUE\t/\tTRUE\t2000000000\tct0\t{x_ct0_clean}\n")
            f.write(f".x.com\tTRUE\t/\tTRUE\t2000000000\tct0\t{x_ct0_clean}\n")

        # 写入 Instagram 的 sessionid 和 csrftoken
        if is_valid_token(ins_token):
            ins_token_clean = ins_token.strip()
            f.write(f".instagram.com\tTRUE\t/\tTRUE\t2000000000\tsessionid\t{ins_token_clean}\n")

        if is_valid_token(ins_csrf):
            ins_csrf_clean = ins_csrf.strip()
            f.write(f".instagram.com\tTRUE\t/\tTRUE\t2000000000\tcsrftoken\t{ins_csrf_clean}\n")

# --- 读取配置并生成Cookie文件 ---
with open("config.yaml", "r", encoding="utf-8") as f:
    config = yaml.safe_load(f)

API_ID = config['TELEGRAM']['API_ID']
API_HASH = config['TELEGRAM']['API_HASH']
BOT_TOKEN = config['TELEGRAM']['BOT_TOKEN']
WORK_DIR = config['SYSTEM']['WORK_DIR']

app = Client("xbot_session", api_id=API_ID, api_hash=API_HASH, bot_token=BOT_TOKEN, workdir=WORK_DIR)
url_cache = {}
active_downloads = {}
generate_unified_cookie_file(config)

# --- 进度条更新任务 ---
async def update_download_ui(message, msg_id):
    last_text = ""
    while msg_id in active_downloads:
        progress = active_downloads[msg_id]
        if progress:
            text = f"⬇️ 正在下载: {progress}"
            if text != last_text:
                try:
                    await message.edit_text(text)
                    last_text = text
                except MessageNotModified:
                    pass
                except Exception:
                    pass
        await asyncio.sleep(3)

async def upload_progress(current, total, message, start_time, state):
    now = time.time()
    if now - state.get('last_update', 0) > 3 or current == total:
        state['last_update'] = now
        
        percent = current * 100 / total
        speed_bps = current / (now - start_time) if now > start_time else 1
        eta_seconds = (total - current) / speed_bps if speed_bps > 0 else 0
        
        current_mb = current / 1024 / 1024
        total_mb = total / 1024 / 1024
        speed_mb = speed_bps / 1024 / 1024
        mins, secs = divmod(int(eta_seconds), 60)
        
        text = (
            f"⬆️ 正在直传至 Telegram:\n"
            f"📊 进度: {percent:.1f}% ({current_mb:.1f} MB / {total_mb:.1f} MB)\n"
            f"🚀 速度: {speed_mb:.2f} MB/s\n"
            f"⏳ 剩余: {mins}分 {secs}秒"
        )
        try:
            await message.edit_text(text)
        except MessageNotModified:
            pass
        except Exception:
            pass

# --- 消息拦截与按钮 ---
@app.on_message(filters.text & ~filters.command("start"))
async def handle_message(client, message):
    url_match = re.search(r'(https?://(?:www\.)?(?:twitter\.com|x\.com)/[^\s]+)', message.text)
    if not url_match:
        return
        
    url = url_match.group(1)
    msg_id = message.id
    url_cache[msg_id] = url
    
    keyboard = InlineKeyboardMarkup([
        [
            InlineKeyboardButton("🎬 视频 (压缩/兼容好)", callback_data=f"video_{msg_id}"),
            InlineKeyboardButton("📄 文件 (无损/原画质)", callback_data=f"doc_{msg_id}")
        ]
    ])
    await message.reply_text('👇 成功解析，请选择接收方式：', reply_markup=keyboard, reply_to_message_id=msg_id)

@app.on_callback_query()
async def button_callback(client, query):
    data = query.data
    chat_id = query.message.chat.id
    
    mode, msg_id_str = data.split('_')
    original_msg_id = int(msg_id_str)
    url = url_cache.get(original_msg_id)
    
    if not url:
        await query.message.edit_text("❌ 链接已过期或丢失，请重新发送。")
        return

    post_id_match = re.search(r'status/(\d+)', url)
    post_id = post_id_match.group(1) if post_id_match else str(original_msg_id)
    
    file_prefix_path = os.path.join(WORK_DIR, f"x_video_{post_id}")
    expected_file_name = f"{file_prefix_path}.mp4"
    
    active_downloads[original_msg_id] = "初始化中..."
    dl_task = asyncio.create_task(update_download_ui(query.message, original_msg_id))
    
    try:
        video_metadata = await asyncio.to_thread(
            download_video_sync, url, file_prefix_path, original_msg_id, active_downloads
        )
        
        active_downloads.pop(original_msg_id, None)
        dl_task.cancel()
        
        if not os.path.exists(expected_file_name):
            raise Exception("yt-dlp 下载完成，但硬盘未找到文件。")

        start_time = time.time()
        state = {"last_update": 0}
        
        if mode == 'video':
            await client.send_video(
                chat_id=chat_id,
                video=expected_file_name,
                reply_to_message_id=original_msg_id,
                caption="✅ Down! 请查收视频！",
                supports_streaming=True,
                width=video_metadata.get('width'),
                height=video_metadata.get('height'),
                duration=video_metadata.get('duration'),
                progress=upload_progress,
                progress_args=(query.message, start_time, state)
            )
        else:
            await client.send_document(
                chat_id=chat_id,
                document=expected_file_name,
                reply_to_message_id=original_msg_id,
                caption="✅ Down! 请查收文件！",
                progress=upload_progress,
                progress_args=(query.message, start_time, state)
            )
            
        await query.message.delete()

    except Exception as e:
        active_downloads.pop(original_msg_id, None)
        if 'dl_task' in locals(): dl_task.cancel()
        await query.message.edit_text(f"❌ 处理失败: {str(e)}")
        
    finally:
        url_cache.pop(original_msg_id, None)
        if os.path.exists(expected_file_name):
            os.remove(expected_file_name)

if __name__ == '__main__':
    print("Main Pyrogram Bot is starting...")
    app.run()
