# main.py
import os
import re
import time
import asyncio
import yaml
import json
from pyrogram import Client, filters
from pyrogram.types import InlineKeyboardMarkup, InlineKeyboardButton
from pyrogram.errors import MessageNotModified

from video_downloader import download_video_sync, probe_video_entries

# --- 将配置文件中的 Token 动态转写为 yt-dlp 可识别的 Netscape 格式 ---
def generate_unified_cookie_file(config):
    system_cfg = config.get('SYSTEM', {})
    tokens = config.get('TOKENS', {})

    # 确定生成的 Cookie 文件路径
    work_dir = system_cfg.get('WORK_DIR', './')
    cookie_filename = system_cfg.get('COOKIE_FILE', 'cookies.txt')
    cookie_path = os.path.join(work_dir, cookie_filename)

    def is_valid_token(token):

        # 1. 检查是否为空或非字符串
        if not token or not isinstance(token, str):
            return False
        token = token.strip()

        # 2. 检查是否为空字符串
        if not token:
            return False

        # 3. 检查是否包含预设的占位符关键字（根据 config.example.yaml 的预设内容）
        invalid_keywords = ["你的", "填这里", "your", "YOUR"]
        if any(keyword in token for keyword in invalid_keywords):
            return False

        # 4. 检查是否包含中文字符 (Token 通常是纯英文/数字/符号)
        if re.search(r'[\u4e00-\u9fa5]', token):
            return False

        # 5. 基础长度校验 (通常 auth_token 和 sessionid 都有一定长度，这里设定一个最低阈值防呆)
        if len(token) < 10:
            return False

        return True


        # 写入文件逻辑
    with open(cookie_path, 'w', encoding='utf-8') as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file is automatically generated by bot. Do not edit manually.\n\n")

        x_token = tokens.get('X_AUTH_TOKEN')
        x_ct0 = tokens.get('X_CT0')

        ins_token = tokens.get('INS_SESSIONID')
        ins_csrf = tokens.get('INS_CSRFTOKEN')

        # 写入 X (Twitter) 的 auth_token 和 ct0
        if is_valid_token(x_token):
            x_token_clean = x_token.strip()
            f.write(f".twitter.com\tTRUE\t/\tTRUE\t2000000000\tauth_token\t{x_token_clean}\n")
            f.write(f".x.com\tTRUE\t/\tTRUE\t2000000000\tauth_token\t{x_token_clean}\n")

        if is_valid_token(x_ct0):
            x_ct0_clean = x_ct0.strip()
            f.write(f".twitter.com\tTRUE\t/\tTRUE\t2000000000\tct0\t{x_ct0_clean}\n")
            f.write(f".x.com\tTRUE\t/\tTRUE\t2000000000\tct0\t{x_ct0_clean}\n")

        # 写入 Instagram 的 sessionid 和 csrftoken
        if is_valid_token(ins_token):
            ins_token_clean = ins_token.strip()
            f.write(f".instagram.com\tTRUE\t/\tTRUE\t2000000000\tsessionid\t{ins_token_clean}\n")

        if is_valid_token(ins_csrf):
            ins_csrf_clean = ins_csrf.strip()
            f.write(f".instagram.com\tTRUE\t/\tTRUE\t2000000000\tcsrftoken\t{ins_csrf_clean}\n")

# --- 读取配置并生成Cookie文件 ---
with open("config.yaml", "r", encoding="utf-8") as f:
    config = yaml.safe_load(f)

API_ID = config['TELEGRAM']['API_ID']
API_HASH = config['TELEGRAM']['API_HASH']
BOT_TOKEN = config['TELEGRAM']['BOT_TOKEN']
WORK_DIR = config['SYSTEM']['WORK_DIR']

app = Client("xbot_session", api_id=API_ID, api_hash=API_HASH, bot_token=BOT_TOKEN, workdir=WORK_DIR)
url_cache = {}
entry_cache = {}
active_downloads = {}
processing_callbacks = set()
generate_unified_cookie_file(config)

# --- 进度条更新任务 ---
async def update_download_ui(message, msg_id):
    last_text = ""
    while msg_id in active_downloads:
        progress = active_downloads[msg_id]
        if progress:
            text = f"⬇️ 正在下载: {progress}"
            if text != last_text:
                try:
                    await message.edit_text(text)
                    last_text = text
                except MessageNotModified:
                    pass
                except Exception:
                    pass
        await asyncio.sleep(3)

async def upload_progress(current, total, message, start_time, state):
    now = time.time()
    if now - state.get('last_update', 0) > 3 or current == total:
        state['last_update'] = now
        
        percent = current * 100 / total
        speed_bps = current / (now - start_time) if now > start_time else 1
        eta_seconds = (total - current) / speed_bps if speed_bps > 0 else 0
        
        current_mb = current / 1024 / 1024
        total_mb = total / 1024 / 1024
        speed_mb = speed_bps / 1024 / 1024
        mins, secs = divmod(int(eta_seconds), 60)
        
        item_text = f"📦 文件: {state['item']}\n" if state.get('item') else ""
        text = (
            f"⬆️ 正在直传至 Telegram:\n"
            f"{item_text}"
            f"📊 进度: {percent:.1f}% ({current_mb:.1f} MB / {total_mb:.1f} MB)\n"
            f"🚀 速度: {speed_mb:.2f} MB/s\n"
            f"⏳ 剩余: {mins}分 {secs}秒"
        )
        try:
            await message.edit_text(text)
        except MessageNotModified:
            pass
        except Exception:
            pass

async def video_codec(file_path):
    """使用 ffprobe 检查视频文件的编码格式"""
    cmd = [
        'ffprobe', '-v', 'error', '-select_streams', 'v:0',
        '-show_entries', 'stream=codec_name', '-of', 'json', file_path
    ]
    try:
        process = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE
        )
        stdout, _ = await process.communicate()
        info = json.loads(stdout)
        return info['streams'][0]['codec_name'].lower()
    except Exception as e:
        print(f"检查编码失败: {e}")
        return ""

def build_file_prefix_path(url, original_msg_id):
    if 'instagram.com' in url:
        ig_match = re.search(r'(?:reel|p)/([^/]+)', url)
        post_id = ig_match.group(1) if ig_match else str(original_msg_id)
        return os.path.join(WORK_DIR, f"ig_video_{post_id}")

    post_id_match = re.search(r'status/(\d+)', url)
    post_id = post_id_match.group(1) if post_id_match else str(original_msg_id)
    return os.path.join(WORK_DIR, f"x_video_{post_id}")

def build_entry_selection_keyboard(mode, original_msg_id, entry_count):
    rows = [[
        InlineKeyboardButton("全部下载", callback_data=f"pick_{mode}_{original_msg_id}_all")
    ]]

    row = []
    for index in range(1, entry_count + 1):
        row.append(InlineKeyboardButton(f"第 {index} 个", callback_data=f"pick_{mode}_{original_msg_id}_{index}"))
        if len(row) == 3:
            rows.append(row)
            row = []

    if row:
        rows.append(row)

    return InlineKeyboardMarkup(rows)

async def transcode_to_h264(message, file_path):
    codec = await video_codec(file_path)
    if codec not in ['vp9', 'vp09', 'av1', 'av01']:
        return

    await message.edit_text("⚙️ 检测到不受支持的视频编码 (VP9/AV1)\n正在自动转码为 H.264，这可能需要几分钟，请耐心等待...")

    file_root, _ = os.path.splitext(file_path)
    transcoded_file = f"{file_root}_h264.mp4"
    ffmpeg_cmd = [
        'ffmpeg', '-y', '-i', file_path,
        '-c:v', 'libx264',
        '-preset', 'veryslow',
        '-crf', '22',
        '-c:a', 'aac',
        '-b:a', '320k',
        transcoded_file
    ]

    process = await asyncio.create_subprocess_exec(
        *ffmpeg_cmd,
        stdout=asyncio.subprocess.DEVNULL,
        stderr=asyncio.subprocess.DEVNULL
    )
    await process.wait()

    if process.returncode == 0 and os.path.exists(transcoded_file):
        os.replace(transcoded_file, file_path)
    else:
        if os.path.exists(transcoded_file):
            os.remove(transcoded_file)
        raise Exception("FFmpeg 转码过程发生错误。")

async def process_download(client, query, mode, original_msg_id, url, selection, entries=None):
    chat_id = query.message.chat.id
    file_prefix_path = build_file_prefix_path(url, original_msg_id)
    downloaded_paths = []
    dl_task = None

    active_downloads[original_msg_id] = "初始化中..."
    dl_task = asyncio.create_task(update_download_ui(query.message, original_msg_id))

    try:
        video_results = await asyncio.to_thread(
            download_video_sync, url, file_prefix_path, original_msg_id, active_downloads, selection, entries
        )

        active_downloads.pop(original_msg_id, None)
        dl_task.cancel()

        if not video_results:
            raise Exception("yt-dlp 未返回任何下载结果。")

        downloaded_paths = [video_metadata['path'] for video_metadata in video_results]
        total_videos = len(video_results)
        for ordinal, video_metadata in enumerate(video_results, start=1):
            file_path = video_metadata['path']

            if not os.path.exists(file_path):
                raise Exception(f"yt-dlp 下载完成，但硬盘未找到文件: {os.path.basename(file_path)}")

            if mode == 'video':
                await transcode_to_h264(query.message, file_path)

            start_time = time.time()
            item_label = f"{ordinal}/{total_videos}" if total_videos > 1 else ""
            state = {"last_update": 0, "item": item_label}
            caption_suffix = f" ({ordinal}/{total_videos})" if total_videos > 1 else ""

            if mode == 'video':
                await client.send_video(
                    chat_id=chat_id,
                    video=file_path,
                    reply_to_message_id=original_msg_id,
                    caption=f"✅ Down! 请查收视频！{caption_suffix}",
                    supports_streaming=True,
                    width=video_metadata.get('width'),
                    height=video_metadata.get('height'),
                    duration=video_metadata.get('duration'),
                    progress=upload_progress,
                    progress_args=(query.message, start_time, state)
                )
            else:
                await client.send_document(
                    chat_id=chat_id,
                    document=file_path,
                    reply_to_message_id=original_msg_id,
                    caption=f"✅ Down! 请查收文件！{caption_suffix}",
                    progress=upload_progress,
                    progress_args=(query.message, start_time, state)
                )

        await query.message.delete()

    except Exception as e:
        active_downloads.pop(original_msg_id, None)
        if dl_task:
            dl_task.cancel()
        await query.message.edit_text(f"❌ 处理失败: {str(e)}")

    finally:
        url_cache.pop(original_msg_id, None)
        entry_cache.pop(original_msg_id, None)
        for file_path in downloaded_paths:
            if os.path.exists(file_path):
                os.remove(file_path)

# --- 消息拦截与按钮 ---
@app.on_message(filters.text & ~filters.command("start"))
async def handle_message(client, message):
    # 匹配 X 和 Instagram 链接
    url_match = re.search(r'(https?://(?:www\.)?(?:twitter\.com|x\.com|instagram\.com)/[^\s]+)', message.text)
    if not url_match:
        return
        
    raw_url = url_match.group(1)
    
    # 直接截断问号及后面的所有跟踪参数（如 ?s=46 或 ?igsh=...）
    clean_url = raw_url.split('?')[0] 
    
    msg_id = message.id
    url_cache[msg_id] = clean_url  # 存入缓存的是“干净”的链接
    
    reply_text = (
        "👇 **成功解析，请选择接收方式：**\n\n"
        "🎬 **视频模式**：可直接预览或保存到相册（VP9 或 AV1 编码会自动触发转码）。\n"
        "📄 **文件模式**：不会损失画质，不触发转码（不支持的编码需要使用第三方播放器）。"
    )

    keyboard = InlineKeyboardMarkup([
        [
            InlineKeyboardButton("🎬 视频模式", callback_data=f"video_{msg_id}"),
        ],
        [
            InlineKeyboardButton("📄 文件模式", callback_data=f"doc_{msg_id}")
        ]
    ])
    await message.reply_text(reply_text, reply_markup=keyboard, reply_to_message_id=msg_id)

@app.on_callback_query()
async def button_callback(client, query):
    data = query.data
    parts = data.split('_')

    if parts[0] == 'pick':
        _, mode, msg_id_str, selection = parts
    else:
        mode, msg_id_str = parts
        selection = None

    original_msg_id = int(msg_id_str)
    url = url_cache.get(original_msg_id)
    
    if not url:
        await query.message.edit_text("❌ 链接已过期或丢失，请重新发送。")
        return

    if original_msg_id in processing_callbacks:
        await query.answer("正在处理，请勿重复点击。", show_alert=False)
        return

    processing_callbacks.add(original_msg_id)
    if selection is not None:
        try:
            cached = entry_cache.get(original_msg_id, {})
            await process_download(client, query, mode, original_msg_id, url, selection, cached.get('entries'))
        finally:
            processing_callbacks.discard(original_msg_id)
        return

    try:
        try:
            cached = entry_cache.get(original_msg_id)
            if cached:
                entries = cached['entries']
            else:
                await query.message.edit_text("🔎 正在检测此链接包含的视频数量...")
                entries = await asyncio.to_thread(probe_video_entries, url)
                entry_cache[original_msg_id] = {
                    'url': url,
                    'mode': mode,
                    'entries': entries,
                    'entry_count': len(entries),
                }
        except Exception as e:
            await query.message.edit_text(f"❌ 解析失败: {str(e)}")
            url_cache.pop(original_msg_id, None)
            entry_cache.pop(original_msg_id, None)
            return

        if len(entries) <= 1:
            await process_download(client, query, mode, original_msg_id, url, 'all', entries)
            return

        await query.message.edit_text(
            f"检测到此 Post 包含 {len(entries)} 个视频，请选择下载范围：",
            reply_markup=build_entry_selection_keyboard(mode, original_msg_id, len(entries))
        )
    finally:
        processing_callbacks.discard(original_msg_id)

if __name__ == '__main__':
    print("Main Pyrogram Bot is starting...")
    app.run()
